name: Format | Doc

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.c"
      - "src/**/*.h"
      - "Doxyfile"
      - ".github/workflows/fmt-doc.yml"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run-format-doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - run: |
          sudo apt install clang-format -y
          clang-format -i -style=file:"src/.clang-format" src/**/*.h  
          clang-format -i -style=file:"src/.clang-format" src/**/*.c
      - uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: 'style: Format code with clang-format'
          commit_user_name: 'gh-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'gh-actions[bot] <github-actions[bot]@users.noreply.github.com>'
      - run: |
          sudo apt install doxygen -y
          doxygen Doxyfile
      - uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/html/

  deploy:
    needs: run-format-doxygen
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: docs/html/
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/html/'
      - uses: actions/deploy-pages@v4
        id: deployment