name: Format | Docs

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.c"
      - "src/**/*.h"
      - "Doxyfile"
      - ".github/workflows/format-docs.yml"

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run clang-format
        run: |
          sudo apt install clang-format -y
          clang-format -i -style=file:"src/.clang-format" src/**/*.h  
          clang-format -i -style=file:"src/.clang-format" src/**/*.c
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: 'style: Format code with clang-format'
          commit_user_name: 'gh-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'gh-actions[bot] <github-actions[bot]@users.noreply.github.com>'

  run-doxygen:
    needs: format-code
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Install Doxygen
        run: |
          sudo apt update
          sudo apt install doxygen -y
      - name: Generate Doxygen documentation
        run: |
          doxygen Doxyfile
      - name: Commit Doxygen documentation
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: 'docs: Update Doxygen documentation'
          commit_user_name: 'gh-actions[bot]'
          commit_user_email: 'action@github.com'
          commit_author: 'gh-actions[bot] <action@github.com>'